### ISSUE TITLE
How to estimate the pose of other animals, and how to use the VisDa2019 data set

### ISSUE THREAD

**Issue by wenwenzhanghaha123wonder** [JitengMu/Learning-from-Synthetic-Animals#8]
Hi！
May I ask you some questions?
How to estimate the pose of other animals, and how to use the VisDa2019 dataset?

**Comment by wenwenzhanghaha123wonder** [comment]
Hi！
How to test the visda2019 data set？I sincerely await your reply.

**Comment by JitengMu** [comment]
Hi, thanks for your interest. 

1. I am not sure if I understand your first question of "other animals" correctly? The method is the same as horse and tiger, where one model is trained for each class. We also provide generated datasets for sheep, dog, and elephants. You may follow the provided data generation section in the repo for other animals.

2.We annotate images from VisDA manually for evaluation only. However, since making it a benchmark is out of the scope of the work, I can not share it here. Please send email to "jmu@ucsd.edu" with title "Questions about Learning from Synthetic Animals" for more details.

**Comment by wenwenzhanghaha123wonder** [comment]
您好，我已经收到您的邮件，谢谢！
